name: "test"

on: [push, pull_request]
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: build
      run: |
        docker build -t lapis-community-test .

    - name: test
      run: |
        docker run lapis-community-test
